### ISSUE TITLE
Image and camera_info topic not in sync

### ISSUE THREAD

**Issue by spirosperos** [berndpfrommer/flir_spinnaker_ros2#36]
I am trying to run apriltag detection using the [ros2 apriltag library](https://github.com/christianrauch/apriltag_ros).
However I am experiencing this warning:

> Topics '/blackfly_0/image_raw' and '/camera_info' do not appear to be synchronized. In the last 10s:
> 	Image messages received:      3
> 	CameraInfo messages received: 7
> 	Synchronized pairs:           2

How can I sync the camera info and the image topic? Thank you.

**Comment by berndpfrommer** [comment]
There's nothing you should have to do, they should be synchronized because the same header stamp is put on when they are published.

But bugs are always an option so let's directly check if the time stamps are good. What do you get when you run simultaneously in two separate terminals:
 
`ros2 topic echo /blackfly_s/camera_info | grep -A 2 stamp`
and
`ros2 topic echo /blackfly_s/image_raw | grep -A 2 stamp`

For me the time stamps line up:

From camera_info:
```
--
  stamp:
    sec: 1677006792
    nanosec: 705401249
```

And from image_raw:
```
--                                           
  stamp:                                     
    sec: 1677006792                          
    nanosec: 705401249   
```
